// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20251123211546_DbCleared")]
    partial class DbCleared
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<double?>("Ocena")
                        .HasColumnType("float");

                    b.Property<int>("Semestr")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KursId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollmenty");
                });

            modelBuilder.Entity("Domain.Entities.Gabinet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NumerGabinetu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProfesorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId")
                        .IsUnique()
                        .HasFilter("[ProfesorId] IS NOT NULL");

                    b.ToTable("Gabinety");
                });

            modelBuilder.Entity("Domain.Entities.Kurs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ECTS")
                        .HasColumnType("int");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProfesorId")
                        .HasColumnType("int");

                    b.Property<int>("WydzialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProfesorId");

                    b.HasIndex("WydzialId");

                    b.ToTable("Kursy");
                });

            modelBuilder.Entity("Domain.Entities.LicznikIndeksow", b =>
                {
                    b.Property<string>("Prefix")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AktualnaWartosc")
                        .HasColumnType("int");

                    b.HasKey("Prefix");

                    b.ToTable("LicznikiIndeksow");
                });

            modelBuilder.Entity("Domain.Entities.Profesor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndeksUczelniany")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TytulNaukowy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WydzialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndeksUczelniany")
                        .IsUnique();

                    b.HasIndex("WydzialId");

                    b.ToTable("Profesorzy");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndeksUczelniany")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RokStudiow")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IndeksUczelniany")
                        .IsUnique();

                    b.ToTable("Studenci");

                    b.HasDiscriminator().HasValue("Student");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Wydzial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Wydzialy");
                });

            modelBuilder.Entity("KursPrerequisite", b =>
                {
                    b.Property<int>("KursId")
                        .HasColumnType("int");

                    b.Property<int>("PrerequisiteId")
                        .HasColumnType("int");

                    b.HasKey("KursId", "PrerequisiteId");

                    b.HasIndex("PrerequisiteId");

                    b.ToTable("KursPrerequisite");
                });

            modelBuilder.Entity("Domain.Entities.StudentStudiowMgr", b =>
                {
                    b.HasBaseType("Domain.Entities.Student");

                    b.Property<int?>("PromotorId")
                        .HasColumnType("int");

                    b.Property<string>("TematPracyDyplomowej")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("PromotorId");

                    b.HasDiscriminator().HasValue("StudentStudiowMgr");
                });

            modelBuilder.Entity("Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("Domain.Entities.Kurs", "Kurs")
                        .WithMany("Enrollmenty")
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Student", "Student")
                        .WithMany("Enrollmenty")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kurs");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Domain.Entities.Gabinet", b =>
                {
                    b.HasOne("Domain.Entities.Profesor", "Profesor")
                        .WithOne("Gabinet")
                        .HasForeignKey("Domain.Entities.Gabinet", "ProfesorId");

                    b.Navigation("Profesor");
                });

            modelBuilder.Entity("Domain.Entities.Kurs", b =>
                {
                    b.HasOne("Domain.Entities.Profesor", "Prowadzacy")
                        .WithMany("ProwadzoneKursy")
                        .HasForeignKey("ProfesorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Wydzial", "Wydzial")
                        .WithMany("Kursy")
                        .HasForeignKey("WydzialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Prowadzacy");

                    b.Navigation("Wydzial");
                });

            modelBuilder.Entity("Domain.Entities.Profesor", b =>
                {
                    b.HasOne("Domain.Entities.Wydzial", "Wydzial")
                        .WithMany("Profesorzy")
                        .HasForeignKey("WydzialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Adres", "AdresZamieszkania", b1 =>
                        {
                            b1.Property<int>("ProfesorId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("KodPocztowy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Miasto")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NumerDomu")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ulica")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("ProfesorId");

                            b1.ToTable("Profesorzy");

                            b1.WithOwner()
                                .HasForeignKey("ProfesorId");
                        });

                    b.Navigation("AdresZamieszkania")
                        .IsRequired();

                    b.Navigation("Wydzial");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Adres", "AdresZamieszkania", b1 =>
                        {
                            b1.Property<int>("StudentId")
                                .HasColumnType("int");

                            b1.Property<int>("Id")
                                .HasColumnType("int");

                            b1.Property<string>("KodPocztowy")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Miasto")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("NumerDomu")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Ulica")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StudentId");

                            b1.ToTable("Studenci");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });

                    b.Navigation("AdresZamieszkania")
                        .IsRequired();
                });

            modelBuilder.Entity("KursPrerequisite", b =>
                {
                    b.HasOne("Domain.Entities.Kurs", null)
                        .WithMany()
                        .HasForeignKey("KursId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Kurs", null)
                        .WithMany()
                        .HasForeignKey("PrerequisiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.StudentStudiowMgr", b =>
                {
                    b.HasOne("Domain.Entities.Profesor", "Promotor")
                        .WithMany()
                        .HasForeignKey("PromotorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Promotor");
                });

            modelBuilder.Entity("Domain.Entities.Kurs", b =>
                {
                    b.Navigation("Enrollmenty");
                });

            modelBuilder.Entity("Domain.Entities.Profesor", b =>
                {
                    b.Navigation("Gabinet")
                        .IsRequired();

                    b.Navigation("ProwadzoneKursy");
                });

            modelBuilder.Entity("Domain.Entities.Student", b =>
                {
                    b.Navigation("Enrollmenty");
                });

            modelBuilder.Entity("Domain.Entities.Wydzial", b =>
                {
                    b.Navigation("Kursy");

                    b.Navigation("Profesorzy");
                });
#pragma warning restore 612, 618
        }
    }
}
